apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler # Type ของ Resource
metadata:
  name: deployment-hpa # ชื่อของ HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-django-app-deployment # ชื่อของ Deployment
  maxReplicas: 3 # จำนวน Pod มากสุด
  minReplicas: 1 # จำนวน Pod น้อยสุด
  targetCPUUtilizationPercentage: 25 # Percent CPU ที่จะให้เริ่ม Scale Pod
